const seedData = [
    {
      product_id: 1,
      product_name: 'Organic Grain-Free Dog Food',
      product_category: 'food',
      product_price: 39.99,
      product_stock: 150,
      product_image: 'https://example.com/dogfood.jpg',
      product_description: 'Premium organic grain-free dog food made with natural ingredients for optimal health and digestion.',
    },
    {
      product_id: 2,
      product_name: 'Interactive Squeaky Dog Toy',
      product_category: 'toys',
      product_price: 12.50,
      product_stock: 200,
      product_image: 'https://example.com/squeakytoy.jpg',
      product_description: 'Durable and interactive squeaky toy for dogs, designed to provide hours of entertainment and mental stimulation.',
    },
    {
      product_id: 3,
      product_name: 'Pet Grooming Kit with Brushes and Clippers',
      product_category: 'grooming',
      product_price: 45.99,
      product_stock: 100,
      product_image: 'https://example.com/groomingkit.jpg',
      product_description: 'Complete pet grooming kit with brushes and clippers for professional grooming sessions at home.',
    },
    {
        product_id: 4,
        product_name: 'Natural Catnip Toy Ball',
        product_category: 'toys',
        product_price: 8.99,
        product_stock: 120,
        product_image: 'https://example.com/catniptoy.jpg',
        product_description: 'All-natural catnip toy ball that encourages exercise and mental stimulation for cats.',
      },
      {
        product_id: 5,
        product_name: 'Grain-Free Salmon Cat Food',
        product_category: 'food',
        product_price: 29.50,
        product_stock: 180,
        product_image: 'https://example.com/salmoncatfood.jpg',
        product_description: 'Nutritious grain-free salmon cat food providing essential nutrients and Omega-3 fatty acids.',
      },
      {
        product_id: 6,
        product_name: 'Dog Rope Chew Toy Set',
        product_category: 'toys',
        product_price: 15.75,
        product_stock: 150,
        product_image: 'https://example.com/ropechewtoys.jpg',
        product_description: 'Set of durable rope chew toys for dogs, aiding dental health and teething relief.',
      },
      {
        product_id: 7,
        product_name: 'Pet Hair Remover Roller',
        product_category: 'grooming',
        product_price: 12.99,
        product_stock: 200,
        product_image: 'https://example.com/hairremover.jpg',
        product_description: 'Efficient pet hair remover roller for furniture and clothing, easy to use and clean.',
      },
      {
        product_id: 8,
        product_name: 'Treat Dispensing Dog Puzzle Toy',
        product_category: 'toys',
        product_price: 17.25,
        product_stock: 130,
        product_image: 'https://example.com/puzzledogtoy.jpg',
        product_description: 'Interactive treat-dispensing puzzle toy for mental stimulation and entertainment for dogs.',
      },
      {
        product_id: 9,
        product_name: 'Natural Cat Litter',
        product_category: 'accessories',
        product_price: 19.99,
        product_stock: 170,
        product_image: 'https://example.com/cat-litter.jpg',
        product_description: 'Biodegradable and odor-absorbing natural cat litter made from sustainable materials.',
      },
      {
        product_id: 10,
        product_name: 'Colorful Bird Perch Swing',
        product_category: 'toys',
        product_price: 9.49,
        product_stock: 100,
        product_image: 'https://example.com/bird-perch.jpg',
        product_description: 'Vibrant and durable perch swing for birds, providing exercise and entertainment.',
      },
      {
        product_id: 11,
        product_name: 'Hamster Exercise Wheel',
        product_category: 'toys',
        product_price: 7.99,
        product_stock: 120,
        product_image: 'https://example.com/hamster-wheel.jpg',
        product_description: 'Quiet and safe exercise wheel designed for hamsters to keep them active and healthy.',
      },
      {
        product_id: 12,
        product_name: 'Nutritious Bird Seed Mix',
        product_category: 'food',
        product_price: 12.75,
        product_stock: 150,
        product_image: 'https://example.com/bird-seed.jpg',
        product_description: 'Healthy and balanced bird seed mix containing a variety of seeds and grains.',
      },
      // Add more entries below
      {
        product_id: 13,
        product_name: 'Hamster Hideout House',
        product_category: 'accessories',
        product_price: 11.99,
        product_stock: 100,
        product_image: 'https://example.com/hamster-house.jpg',
        product_description: 'Cozy hideout house for hamsters providing a safe and comfortable resting place.',
      },
      {
        product_id: 14,
        product_name: 'Bird Cage Perch Set',
        product_category: 'accessories',
        product_price: 18.50,
        product_stock: 90,
        product_image: 'https://example.com/bird-cage-perch.jpg',
        product_description: 'Set of assorted perches for bird cages, offering variety and stimulation for birds.',
      },
      {
        product_id: 15,
        product_name: 'Hamster Chew Toys Bundle',
        product_category: 'toys',
        product_price: 14.25,
        product_stock: 110,
        product_image: 'https://example.com/hamster-chew-toys.jpg',
        product_description: 'Bundle of chew toys designed to promote dental health and prevent boredom in hamsters.',
      },

  ];
  
  console.log(seedData);